openapi: 3.0.0
info:
  title: DailyReport
  version: '1.0'
  contact:
    email: watertrans@gmail.com
    name: Masahisa Kobayashi
    url: 'https://github.com/watertrans'
  license:
    name: MIT
    url: 'https://github.com/watertrans/DailyReport/blob/main/LICENSE'
  description: The daily report Web API specfications.
servers:
  - url: 'https://localhost:44350/api/v1'
paths:
  /token:
    post:
      summary: アクセストークン発行
      operationId: post-token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
      description: アクセストークンを発行します。
      security: []
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                    - client_credentials
                  example: client_credentials
                  description: 権限種別
                scope:
                  type: string
                  description: スコープ
                  enum:
                    - fullcontrol
                    - read
                    - write
                client_id:
                  type: string
                  description: クライアントID
                  example: owner
                client_secret:
                  type: string
                  description: クライアントシークレット
                  example: owner-secret
              required:
                - grant_type
            examples:
              client_credentials:
                value:
                  grant_type: client_credentials
                  client_id: owner
                  client_secret: owner-secret
        description: ''
      tags:
        - Token
components:
  schemas:
    Error:
      title: Error
      type: object
      x-examples:
        NotFound:
          message: 指定したリソースは存在しません。
          code: NotFound
        ValidationError:
          code: ValidationError
          message: 入力エラーが発生しました。エラーメッセージを確認してください。
          details:
            - message: '''ステータス''の値が正しくありません。'
              target: status
              code: ValidationErrorDetail
      description: エラー
      properties:
        code:
          type: string
          description: エラーコード
        message:
          type: string
          description: エラーメッセージ
        details:
          type: array
          description: エラー詳細
          items:
            $ref: '#/components/schemas/Error'
        target:
          type: string
          description: エラーターゲット
        innerError:
          $ref: '#/components/schemas/Error'
      required:
        - code
        - message
    Person:
      title: Person
      type: object
      description: 従業員
      x-examples:
        John Doe:
          personId: f3e5ff26-28ff-4cd6-9b1b-e303a185a13a
          personCode: '000001'
          name: John Doe
          title: Human Resources Manager
          description: 'Hire date: 2010.04.01'
          status: NORMAL
          sortNo: 0
          tags:
            - Human Resources
            - Manager
            - '2010'
      properties:
        personId:
          type: string
          description: 従業員ID
          format: uuid
        personCode:
          type: string
          description: 従業員コード
          maxLength: 20
        name:
          type: string
          maxLength: 100
          description: 名前
        title:
          type: string
          description: 役職
          maxLength: 100
        description:
          type: string
          description: 説明
          maxLength: 400
        status:
          type: string
          enum:
            - NORMAL
            - SUSPENDED
          description: ステータス
        sortNo:
          type: integer
          description: 並び順
          minimum: 0
          exclusiveMaximum: false
          maximum: 2147483647
        tags:
          type: array
          format: date
          description: The date that the user was created.
          minItems: 0
          maxItems: 10
          uniqueItems: true
          items:
            type: string
            maxLength: 100
      required:
        - personId
        - personCode
        - title
        - description
        - status
        - sortNo
        - tags
        - name
    Token:
      title: Token
      type: object
      description: アクセストークン
      properties:
        access_token:
          type: string
          description: アクセストークン
          maxLength: 100
        expires_in:
          type: integer
          description: アクセストークンの存続時間（秒単位）
        token_type:
          type: string
          description: トークンタイプ
        scope:
          type: string
          description: スコープ
      required:
        - access_token
        - expires_in
        - token_type
        - scope
      x-examples:
        Bearer:
          access_token: HP89YjM-tUqS8In7Av2L2gqQlIWtLxb06fNrp3WU58Kw
          expires_in: 3600
          token_type: Bearer
          scope: full_control read write
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
  responses:
    400BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                $ref: '#/components/schemas/Error'
    401Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                $ref: '#/components/schemas/Error'
    403Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                $ref: '#/components/schemas/Error'
    404NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                $ref: '#/components/schemas/Error'
    500InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                $ref: '#/components/schemas/Error'
security:
  - Bearer: []
tags:
  - name: Debug
  - name: Person
  - name: Token
