//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterTrans.DailyReport.Web.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaterTrans.DailyReport.Web.Api.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は重複登録できません。.
        /// </summary>
        public static string DataAnnotationDuplicatedStringArray {
            get {
                return ResourceManager.GetString("DataAnnotationDuplicatedStringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の値が正しくありません。.
        /// </summary>
        public static string DataAnnotationEnumContains {
            get {
                return ResourceManager.GetString("DataAnnotationEnumContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の値が正しくありません。.
        /// </summary>
        public static string DataAnnotationEnumDataType {
            get {
                return ResourceManager.GetString("DataAnnotationEnumDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の値が正しくありません。.
        /// </summary>
        public static string DataAnnotationGuid {
            get {
                return ResourceManager.GetString("DataAnnotationGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は{1}個以内で入力してください。.
        /// </summary>
        public static string DataAnnotationMaxLength {
            get {
                return ResourceManager.GetString("DataAnnotationMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は{1}以上{2}以下で入力してください。.
        /// </summary>
        public static string DataAnnotationRange {
            get {
                return ResourceManager.GetString("DataAnnotationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;を入力してください。.
        /// </summary>
        public static string DataAnnotationRequired {
            get {
                return ResourceManager.GetString("DataAnnotationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;を入力してください。.
        /// </summary>
        public static string DataAnnotationRequiredStringArray {
            get {
                return ResourceManager.GetString("DataAnnotationRequiredStringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;に指定可能な項目リストを確認してください。.
        /// </summary>
        public static string DataAnnotationSort {
            get {
                return ResourceManager.GetString("DataAnnotationSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は{1}文字以内で入力してください。.
        /// </summary>
        public static string DataAnnotationStringLength {
            get {
                return ResourceManager.GetString("DataAnnotationStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;は{1}文字以内で入力してください。.
        /// </summary>
        public static string DataAnnotationStringLengthArray {
            get {
                return ResourceManager.GetString("DataAnnotationStringLengthArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 権限種別.
        /// </summary>
        public static string DisplayCommonGrantType {
            get {
                return ResourceManager.GetString("DisplayCommonGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除データを含む.
        /// </summary>
        public static string DisplayCommonIncludeDeleted {
            get {
                return ResourceManager.GetString("DisplayCommonIncludeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページ番号.
        /// </summary>
        public static string DisplayCommonPage {
            get {
                return ResourceManager.GetString("DisplayCommonPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページサイズ.
        /// </summary>
        public static string DisplayCommonPageSize {
            get {
                return ResourceManager.GetString("DisplayCommonPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索キーワード.
        /// </summary>
        public static string DisplayCommonQuery {
            get {
                return ResourceManager.GetString("DisplayCommonQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 並び順.
        /// </summary>
        public static string DisplayCommonSort {
            get {
                return ResourceManager.GetString("DisplayCommonSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 説明.
        /// </summary>
        public static string DisplayPersonDescription {
            get {
                return ResourceManager.GetString("DisplayPersonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前.
        /// </summary>
        public static string DisplayPersonName {
            get {
                return ResourceManager.GetString("DisplayPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 従業員コード.
        /// </summary>
        public static string DisplayPersonPersonCode {
            get {
                return ResourceManager.GetString("DisplayPersonPersonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 従業員ID.
        /// </summary>
        public static string DisplayPersonPersonId {
            get {
                return ResourceManager.GetString("DisplayPersonPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 並び順.
        /// </summary>
        public static string DisplayPersonSortNo {
            get {
                return ResourceManager.GetString("DisplayPersonSortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ステータス.
        /// </summary>
        public static string DisplayPersonStatus {
            get {
                return ResourceManager.GetString("DisplayPersonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タグ.
        /// </summary>
        public static string DisplayPersonTags {
            get {
                return ResourceManager.GetString("DisplayPersonTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 肩書き.
        /// </summary>
        public static string DisplayPersonTitle {
            get {
                return ResourceManager.GetString("DisplayPersonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証トークンの有効期限が切れています。.
        /// </summary>
        public static string ErrorResultAuthorizationTokenExpired {
            get {
                return ResourceManager.GetString("ErrorResultAuthorizationTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要求が正しくありません。.
        /// </summary>
        public static string ErrorResultBadRequest {
            get {
                return ResourceManager.GetString("ErrorResultBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定した操作を実行するアクセス権がありません。.
        /// </summary>
        public static string ErrorResultForbidden {
            get {
                return ResourceManager.GetString("ErrorResultForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーで予期しないエラーが発生しました。.
        /// </summary>
        public static string ErrorResultInternalServerError {
            get {
                return ResourceManager.GetString("ErrorResultInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証スキームが正しくありません。.
        /// </summary>
        public static string ErrorResultInvalidAuthorizationScheme {
            get {
                return ResourceManager.GetString("ErrorResultInvalidAuthorizationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証トークンが正しくありません。.
        /// </summary>
        public static string ErrorResultInvalidAuthorizationToken {
            get {
                return ResourceManager.GetString("ErrorResultInvalidAuthorizationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クライアントの認証に失敗しました。.
        /// </summary>
        public static string ErrorResultInvalidClient {
            get {
                return ResourceManager.GetString("ErrorResultInvalidClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 権限種別が正しくありません。.
        /// </summary>
        public static string ErrorResultInvalidGrantType {
            get {
                return ResourceManager.GetString("ErrorResultInvalidGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スコープが正しくありません。.
        /// </summary>
        public static string ErrorResultInvalidScope {
            get {
                return ResourceManager.GetString("ErrorResultInvalidScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証ヘッダーを指定してください。.
        /// </summary>
        public static string ErrorResultNoAuthorizationHeader {
            get {
                return ResourceManager.GetString("ErrorResultNoAuthorizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定したリソースは存在しません。.
        /// </summary>
        public static string ErrorResultNotFound {
            get {
                return ResourceManager.GetString("ErrorResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 認証情報が正しくありません。.
        /// </summary>
        public static string ErrorResultUnauthorized {
            get {
                return ResourceManager.GetString("ErrorResultUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力エラーが発生しました。エラーメッセージを確認してください。.
        /// </summary>
        public static string ErrorResultValidationError {
            get {
                return ResourceManager.GetString("ErrorResultValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;に指定した&apos;{1}&apos;に対応するデータが存在しません。.
        /// </summary>
        public static string ValidationDataNotFound {
            get {
                return ResourceManager.GetString("ValidationDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;の値はすでに登録されています。.
        /// </summary>
        public static string ValidationDuplicated {
            get {
                return ResourceManager.GetString("ValidationDuplicated", resourceCulture);
            }
        }
    }
}
